name: screwed
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Doug Bell <email@example.com>

environment:
  sdk: '>=2.0.0-dev.48.0 <2.0.0'

#dependencies:
#  resource: ^2.1.2
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.8.9
  build_web_compilers: ^0.4.0
